# Generated by Django 3.0 on 2019-12-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_auto_20191208_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='created_at',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
